spring:
  application:
    name: hello-eureka-service
server:
  port: 8181
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8180/eureka/
  server:
    # 关闭保护机制，确保注册中心可以将不可用的实例正确剔除
    enable-self-preservation: false
management:
  endpoint:
    shutdown:
      enabled: true