server:
  port: 8080
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zengs01/spring-cloud-example
          search-paths: cloud-config-server/config-repo
          username: zengs01
          password: agile1631@163.com